### ISSUE TITLE
Unsuccessful Installation using create-scst.sh on Ubuntu 16.04 (kernel 4.4)

### ISSUE THREAD

**Issue by jibundit** [gstanden/orabuntu-lxc#104]
An upgrade to HWE is successful, but create-scst-install.sh and create-scst-dkms.sh could not install module of scst, thus causing scst.service could not start then.
[create-scst-dkms.log](https://github.com/gstanden/orabuntu-lxc/files/1595892/create-scst-dkms.log)

**Comment by jibundit** [comment]
My workaround is to build scst (under `orabuntu-lxc-master/orabuntu/archives/scst-files/scst-3.4.0` again, and reboot.

**Comment by gstanden** [comment]
@jbundit sorry I did not reply to this sooner I have been finishing and releasing Orabuntu-LXC v5.34-beta!  Thank you for the comment and update.  The HWE for 16.04 should all be automated and should not have this problem.  I have tested it previously and it worked fine after the HWE was installed.  However, based on your results I will retest this and post here with results to re-verify this install case for the HWE kernel on 16.04 ubuntu.

**Comment by gstanden** [comment]
@jibundit I tested it and had no issues.  I created a video on youtube documenting the entire build and install of the DKMS packages using Orabuntu-LXC scst-files.tar bundle for the Ubuntu 16.04 HWE use case here:  https://youtu.be/KIGoyT0YZqw  HTH Gilbert Standen.

**Comment by gstanden** [comment]
Hey just an update @jibundit scst-files.tar now supports the vanilla 16.04 kernels (4.4.x series) so there is no need to install the HWE kernel anymore.  This is because SCST developer Bart VanAssche has created new functionality to create the DKMS packages.  Info is here:  https://sites.google.com/site/nandydandyoracle/scst/scst-debian-dkms-package-build-from-source-ubuntu-17-04 Thanks
